### ISSUE TITLE
custom-version doesn't bypass Bukkit permissions

### ISSUE THREAD

**Issue by TheIntelloBox** [DoNotSpamPls/eZProtector#8] opened 2018-05-19 17:28 UTC
```
custom-version:
  # If you enable this, the other three options will *not* work!
  enabled: true
  version: "SpeedCraft 1.7.x à 1.13"
  # If the enabled option above is set to false, this message will be shown instead.
  error-message: '%prefix% &4You are not allowed to see this server''s version.'
  notify-admins:
    enabled: false
    message: '%prefix% %player% tried to see the server version'
  # The punish feature will only work if you have the custom-version feature set to false.
  punish-player:
    enabled: false
    command: 'kick %player% %prefix% You don''t have permission to do this. (%command%)'
```

But if my player does /version, it says that he doesn't have the permission.

**Comment by DoNotSpamPls** [comment] 2018-05-23 18:14
It's possible that the command doesn't bypass Bukkit permissions (now that I think about it, I may know the cause, but I don't have time and this will need testing), try giving the player "bukkit.command.version" and it should work for now.

**Comment by DoNotSpamPls** [comment] 2018-05-25 10:34
Okay, I tested it, and it seems that eZProtector is bypassing Bukkit permissions just fine. Please try changing your jar to the latest version on Spigot and try again.

**Comment by TheIntelloBox** [comment] 2018-05-25 19:38
I'm using Paper Spigot. Could you check with this version ?

**Comment by TheIntelloBox** [comment] 2018-05-30 16:08
If I check on Bukkit Page : 
bukkit.command.version: Permission Default 

So EzProtector is the problem.

**Comment by TheIntelloBox** [comment] 2018-05-31 19:15
Bug fixed I think.

**Comment by DoNotSpamPls** [comment] 2018-06-03 10:39
I really can't reproduce this issue, so it must be a problem in your implementation. Closing the issue.

**Closed as completed by DoNotSpamPls** 2018-06-03 10:39 UTC
Labels: bug, can't reproduce
