### ISSUE TITLE
Plugin failed to load protection

### ISSUE THREAD

**Issue by TheWranger** [DoNotSpamPls/eZProtector#9] opened 2018-05-20 13:56 UTC
**Describe the feature you'd like to have implemented**
A configurable system that detects when a plugin fails to load and disables itself (shows up red in /plugins) and runs a set configurable commands when it does. Many servers auto-restart every 8 or so hours and there's always the chance that something could go wrong on each startup (or even while the server is running).

Would also like to see a configurable blacklist or whitelist for this so we can choose specifically what plugins to check.

**Comment by DoNotSpamPls** [comment] 2018-05-20 17:33
I don't see the point of this. If a plugin doesn't load, that means there's something wrong and you should fix it. Sorry, but I won't be adding this.

**Closed as completed by DoNotSpamPls** 2018-05-20 17:33 UTC
Labels: enhancement, wontfix

**Comment by TheWranger** [comment] 2018-05-20 23:01
The owner can't be online 24/7 when the server restarts. If something fails to boot up then players can abuse it.

**Comment by DoNotSpamPls** [comment] 2018-05-24 15:18
If a plugin isn't loading, then you should remove it until the issue is fixed. In my 5+ years being involved with Minecraft servers, I've never seen a plugin refuse to load without a reason, and that reason should be found and fixed by the server admin. This plugin can't fix stupid behaviour.

If you want this feature so much, you could ask the Spigot community to make a small plugin for you - here is a small snippet of code that will make it work 😃 
```
for (Plugin plugin : Bukkit.getServer().getPluginManager().getPlugins()) { 
    if (!plugin.isEnabled()) { 
        // execute commands
    } 
}
```
